server:
  port: 5000

spring:
  application:
    name: keystone-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/keystonedb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:54321}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: keystone_super_secret_jwt_key_2026_real_estate_advisor_security_key_must_be_long
    expiration-ms: 86400000
  upload-dir: public/uploads
